# Generated by Django 4.1 on 2022-08-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-05-14'),
            preserve_default=False,
        ),
    ]
